import { Providers } from "@/app/core/client/context";
import { Metadata } from "next";
import "@/app/globals.css";
import { Suspense } from "react";
import Loading from "./loading";
export const metadata: Metadata = {
  title: "Nextjs Playground",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ lang: string }>;
}) {
  const { lang } = await params;
  return (
    <html lang={lang} suppressHydrationWarning>
      <body suppressHydrationWarning>
        <Providers lang={lang}>
          <Suspense fallback={<Loading />}>{children}</Suspense>
        </Providers>
      </body>
    </html>
  );
}
