import { Providers } from "@/app/core/client/context";
import { Metadata } from "next";
import "@/app/globals.css";
import { Suspense } from "react";
import Loading from "./loading";
import GlobalTheme from "../components/GlobalTheme";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          <Suspense fallback={<Loading />}>
            <GlobalTheme>{children}</GlobalTheme>
          </Suspense>
        </Providers>
      </body>
    </html>
  );
}
